#!/bin/bash
echo "Please select a Database:"
options=( $(ls data) )

menu(){
select opt in "${options[@]}" "Quit" ; do 
    if (( REPLY == 1 + ${#options[@]} )) ; then
        . ./menu

    elif (( REPLY > 0 && REPLY <= ${#options[@]} )) ; then
        echo  "You picked $opt Database"	
	export $opt
        . ./databasemenu $opt
       	

    else
        echo "Invalid option. Try another one."
    fi
done  
}
menu

