#!/bin/bash
echo "Choose command"


show_menu(){
select c in 'Show all databases' 'Create new database' 'connect to database' 'Exit'
do
if [[ $c = "Show all databases" ]] 
then
ls data
break;
elif [[ $c = "Create new database" ]] 
then
echo "Please enter database name"
while [[ true ]]; do
read dbName;
directory="data/$dbName"
if [ -d "$directory" ]; then
    echo "This database is already created, Please Enter another name"
   		
else 
    mkdir "data/$dbName"
	break;	
fi
done
break;
elif [[ $c = "connect to database" ]] 
then
. ./connectToDatabase
break 
elif [[ $c = "Exit" ]] 
then
exit
fi
done
}
while true
do
show_menu
done
